import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Sidebar from "@/src/components/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen grid grid-rows-[auto_1fr] grid-cols-[250px_1fr]">
          <header className="col-span-2 bg-transparent p-4 flex items-center gap-3">
            <Image src="/jblogo.png" alt="Logo" width={40} height={40} />
            <span className="text-xl font-semibold">Dashboard Manager</span>
          </header>
          <aside className="bg-transparent p-4">
            <Sidebar />
          </aside>
          <main className="p-4 overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
